name: Deploy to Netlify

on:
  push:
    branches: [ "main" ]
    paths:
      - src/app/**
      - src/assets/**
      - src/main.ts
      - src/env.d.ts
      - src/polyfills.ts
      - src/styles.scss
      - src/index.html
      - angular.json
      - package.json
      - tsconfig.app.json
      - tsconfig.json
      - tsconfig.spec.json

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Node.js 16.x
      uses: actions/setup-node@v3
      with:
        node-version: 16.x
        cache: 'npm'
    - name: Install dependencies
      run: npm ci
    - name: Set up environment variables
      run: | 
        echo "NG_APP_COGNITO_USER_POOL_ID=$COGNITO_USER_POOL_ID" > .env
        echo "NG_APP_COGNITO_USER_POOL_CLIENT_ID=$COGNITO_USER_POOL_CLIENT_ID" >> .env
      env:
        COGNITO_USER_POOL_ID: ${{ secrets.COGNITO_USER_POOL_ID }}
        COGNITO_USER_POOL_CLIENT_ID: ${{ secrets.COGNITO_USER_POOL_CLIENT_ID }}
    - name: Build
      run: npm run build
    - name: Deploy to Netlify
      uses: netlify/actions/cli@master
      with:
        args: deploy --dir=dist/ordlista --prod
      env:
        NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
